# This file was generated by GoReleaser. DO NOT EDIT.
cask "omni" do
  version "0.9.7"

  on_macos do
    on_intel do
      sha256 "b6d64d4a30142b56036a23fb8157154972a2b93164c96a8f11ab953a9239a085"
      url "https://github.com/lkshrk/omni/releases/download/v#{version}/omni_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "d4f7b27b5c7bd4eb2267dabb17d078e5cf0c351e56faa45d416bde099c00c83f"
      url "https://github.com/lkshrk/omni/releases/download/v#{version}/omni_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9358ff63b502478f3d061981a058192c6a14c84ec53d511a84615dca8a0ee7db"
      url "https://github.com/lkshrk/omni/releases/download/v#{version}/omni_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "12f9f14a4d0872c4fb5504033c545ab3b25a0d42002ff6f4527666fa34483802"
      url "https://github.com/lkshrk/omni/releases/download/v#{version}/omni_linux_arm64.tar.gz"
    end
  end

  name "omni"
  desc "Manage all your dev tools from a single JSON config file."
  homepage "https://github.com/lkshrk/omni"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "stow",
    ]

  binary "omni"

  # No zap stanza required

end
