# This file was generated by GoReleaser. DO NOT EDIT.
cask "omni" do
  version "0.9.8"

  on_macos do
    on_intel do
      sha256 "d4156a08c9b45e49eadc6c31095f21236d98bfd3eadcb964ecd37dc073d9cbae"
      url "https://github.com/lkshrk/omni/releases/download/v#{version}/omni_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "a7e3f31b1760b163252cf685f32a90b782ee6c6970935be1a0c9d0a660a1a4ef"
      url "https://github.com/lkshrk/omni/releases/download/v#{version}/omni_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7a8457ba07df17b8f0579904c90b819f329f1973f1394dbdc116f3dde8b2edb0"
      url "https://github.com/lkshrk/omni/releases/download/v#{version}/omni_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "76f9990c3b590936071e27c43222ca5562eac9ba78ece1055d7a73ff904f8bf4"
      url "https://github.com/lkshrk/omni/releases/download/v#{version}/omni_linux_arm64.tar.gz"
    end
  end

  name "omni"
  desc "Manage all your dev tools from a single JSON config file."
  homepage "https://github.com/lkshrk/omni"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "stow",
    ]

  binary "omni"

  # No zap stanza required

end
