# This file was generated by GoReleaser. DO NOT EDIT.
cask "omni" do
  version "0.9.6"

  on_macos do
    on_intel do
      sha256 "5221861fd56f1f92ebc46f231eba501a685f68432bd7962bc0deb3833e8d7dd3"
      url "https://github.com/lkshrk/omni/releases/download/v#{version}/omni_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "517cbf3f1d84b303aecdcda99d97b6138c2189ee9628f682c304db6aeee1d495"
      url "https://github.com/lkshrk/omni/releases/download/v#{version}/omni_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fe3322929096326aab1b30c0938b99590568a4098a8a149d072ba9abef57f630"
      url "https://github.com/lkshrk/omni/releases/download/v#{version}/omni_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "2dd02641186341e1c88c354406bcce788ec04cebef5e2ebe454c86cc03820a5f"
      url "https://github.com/lkshrk/omni/releases/download/v#{version}/omni_linux_arm64.tar.gz"
    end
  end

  name "omni"
  desc "Manage all your dev tools from a single JSON config file."
  homepage "https://github.com/lkshrk/omni"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "stow",
    ]

  binary "omni"

  # No zap stanza required

end
