# This file was generated by GoReleaser. DO NOT EDIT.
cask "ops-pilot" do
  depends_on formula: "git"

  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "6c0944645512a091fc2f8902c436ce3608718e147c8185055497c379d9de9275"
      url "https://github.com/lkshrk/Ops-Pilot/releases/download/v#{version}/ops-pilot_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7b148e57dba0deb8101052fe3a1c2c4af8a914ae0c388ca0792a0c46400ef58e"
      url "https://github.com/lkshrk/Ops-Pilot/releases/download/v#{version}/ops-pilot_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "889890fd466d331e38e3a34b6db91a79cc5999c3a1fffff7090f2a2adb896645"
      url "https://github.com/lkshrk/Ops-Pilot/releases/download/v#{version}/ops-pilot_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0309bf0ecfabce8a99b5522f631b640a24d016092771e37e3ec40c5c38e07174"
      url "https://github.com/lkshrk/Ops-Pilot/releases/download/v#{version}/ops-pilot_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ops-pilot"
  desc "Merges, watches and reverts Renovate updates in a Flux GitOps repository"
  homepage "https://github.com/lkshrk/Ops-Pilot"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ops-pilot"

  # No zap stanza required

end
