# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Omni < Formula
  desc "Manage all your dev tools from a single JSON config file."
  homepage "https://github.com/lkshrk/omni"
  version "0.7.1"
  license "MIT"

  depends_on "stow"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lkshrk/omni/releases/download/v0.7.1/omni_darwin_x86_64.tar.gz"
      sha256 "0d369f3fc46f2331294f581c44cff1312e7f4c5820be32fd7dfb64c16cb3ac36"

      define_method(:install) do
        bin.install "omni"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lkshrk/omni/releases/download/v0.7.1/omni_darwin_arm64.tar.gz"
      sha256 "d6e8938d5a47ca97385b2d9cbe2cd7b2f1f5a2503df0a0aa13ad0065131e1ebd"

      define_method(:install) do
        bin.install "omni"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lkshrk/omni/releases/download/v0.7.1/omni_linux_x86_64.tar.gz"
      sha256 "90f91adc4fc5be6bea573ff62d43b315bca7a090347095efebcd280f1bc07ba1"
      define_method(:install) do
        bin.install "omni"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lkshrk/omni/releases/download/v0.7.1/omni_linux_arm64.tar.gz"
      sha256 "585e7e70025178ace7e40d0e6873b8e96dda479a077170bd2f73220402049f0b"
      define_method(:install) do
        bin.install "omni"
      end
    end
  end

  test do
    system "#{bin}/omni", "--version"
  end
end
