# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Omni < Formula
  desc "Manage all your dev tools from a single JSON config file."
  homepage "https://github.com/lkshrk/omni"
  version "0.8.2"
  license "MIT"

  depends_on "stow"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lkshrk/omni/releases/download/v0.8.2/omni_darwin_x86_64.tar.gz"
      sha256 "36a3de672a3670bfb5320f38429d09a04e9cb998e5278ef50818a1e7815b6062"

      define_method(:install) do
        bin.install "omni"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lkshrk/omni/releases/download/v0.8.2/omni_darwin_arm64.tar.gz"
      sha256 "b1f84483ff4c1c40264b29e68a73ebf6db6cbc074fee95fd5f2f2ba970352c8e"

      define_method(:install) do
        bin.install "omni"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lkshrk/omni/releases/download/v0.8.2/omni_linux_x86_64.tar.gz"
      sha256 "0ee3def4bbde23359152f2cf377d7ff159f8abc4d7976c97325ecc09ca1d4dad"
      define_method(:install) do
        bin.install "omni"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lkshrk/omni/releases/download/v0.8.2/omni_linux_arm64.tar.gz"
      sha256 "1d482a1205dc51d5753feb08aefca8b27c5838444ea5a64297d2509441c5f487"
      define_method(:install) do
        bin.install "omni"
      end
    end
  end

  test do
    system "#{bin}/omni", "--version"
  end
end
